### ISSUE TITLE
Trailing space crash on Windows

### ISSUE THREAD

**Issue by marcederis** [siom79/jdrivesync#13]
Hello,

This bug only seems to affect Windows machines, and does not seem to affect Unix machines.

Files with a trailing space character crash the program on Windows:

```
2015-11-12 14:06:09 SEVERE jdrivesync.App main(): The following error occurred: Trailing char < > at index 18: c:\sync\38889-PT
java.nio.file.InvalidPathException: Trailing char < > at index 18: c:\sync\38889-PT
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.io.File.toPath(Unknown Source)
        at jdrivesync.fs.FileSystemAdapter.createDirectory(FileSystemAdapter.java:134)
        at jdrivesync.sync.Synchronization$2.createLocalDir(Synchronization.java:478)
        at jdrivesync.sync.Synchronization$2.processRemoteFilesWithoutLocalFile(Synchronization.java:359)
        at jdrivesync.sync.Synchronization$2.visitDirectory(Synchronization.java:340)
        at jdrivesync.gdrive.GoogleDriveWalker.walkInternal(GoogleDriveWalker.java:87)
        at jdrivesync.gdrive.GoogleDriveWalker.walk(GoogleDriveWalker.java:34)
        at jdrivesync.sync.Synchronization.syncDown(Synchronization.java:315)
        at jdrivesync.App.sync(App.java:95)
        at jdrivesync.App.run(App.java:53)
        at jdrivesync.App.main(App.java:26)
```

**Comment by siom79** [comment]
Released with version 0.3.0.
