### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Required array size too large

### ISSUE THREAD

**Issue by core-education** [siom79/jdrivesync#14]
Hi

We are using this to sync a large amount of data (currently 131,899 Files, 16.9 TB). It seemed to work fine with the initial upload to google drive, but now it gets around 5.5TB through (mostly unchanged files) then crashes with the following:

Exception in thread "main" java.lang.OutOfMemoryError: Required array size too large
        at java.nio.file.Files.readAllBytes(Unknown Source)
        at jdrivesync.sync.Synchronization.computeMd5Checksum(Synchronization.java:284)
        at jdrivesync.sync.Synchronization.access$300(Synchronization.java:35)
        at jdrivesync.sync.Synchronization$1.performChecksumCheck(Synchronization.java:257)
        at jdrivesync.sync.Synchronization$1.processRemoteChildFound(Synchronization.java:178)
        at jdrivesync.sync.Synchronization$1.visitDirectory(Synchronization.java:68)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:57)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:64)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:64)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:64)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:64)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:64)
        at jdrivesync.fs.FileSystemWalker.walkInternal(FileSystemWalker.java:64)
        at jdrivesync.fs.FileSystemWalker.walk(FileSystemWalker.java:33)
        at jdrivesync.sync.Synchronization.syncUp(Synchronization.java:50)
        at jdrivesync.App.sync(App.java:93)
        at jdrivesync.App.run(App.java:53)
        at jdrivesync.App.main(App.java:26)

Windows Server 2012 R2, Java 8 Update 66 - x64

**Comment by siom79** [comment]
I guess the file that causes this error is a huge one. As a first workaround you can either ignore the file (add it to the ignore list) or you increase the amount of memory for the Java Virtual Machine by setting the parameter `-Xmx` to for example 8 GB with `-Xmx8g`:

```
java -Xmx8g https://github.com/siom79/jdrivesync.git ...
```

I will fix this ASAP.

**Comment by siom79** [comment]
Released with version 0.3.0.

**Comment by core-education** [comment]
Cheers
