### ISSUE TITLE
Parameter max file size fails

### ISSUE THREAD

**Issue by OriolLopezMassaguer** [siom79/jdrivesync#23]
[oriol@homer soft]$ java -Xmx8G -jar jdrivesync-0.4.1-jar-with-dependencies.jar -m -1000 -d -l /phi/users/oriol/gdrive_upf/ -r /
....
2017-11-28 12:33:04 GRAVE jdrivesync.App main(): The following error occurred: null
java.lang.NullPointerException
        at java.lang.Long.compareTo(Long.java:1234)
        at jdrivesync.gdrive.GoogleDriveWalker.fileShouldBeIgnored(GoogleDriveWalker.java:123)
        at jdrivesync.gdrive.GoogleDriveWalker.walkInternal(GoogleDriveWalker.java:81)
        at jdrivesync.gdrive.GoogleDriveWalker.walk(GoogleDriveWalker.java:35)
        at jdrivesync.sync.Synchronization.syncDown(Synchronization.java:321)
        at jdrivesync.App.sync(App.java:89)
        at jdrivesync.App.run(App.java:54)
        at jdrivesync.App.main(App.java:27)

**Comment by siom79** [comment]
Fixed in 0.5.0
